{% set name = "streamlit_tags" %}
{% set version = "1.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streamlit_tags-{{ version }}.tar.gz
  sha256: 9ea46b21f206dc73164e59e3c800a96c863c90af57afde20115f001a6d986583

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - streamlit >=0.63

test:
  imports:
    - streamlit_tags
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/gagan3012/streamlit-tags
  summary: Tags custom component for Streamlit
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - gagan3012
